const ciudades = [
    {
        "id": 1,
        "image": "https://dam.ngenespanol.com/wp-content/uploads/2019/06/Beijing-china.png",
        "name": "Beijing",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "China",
    },
    {
        "id": 2,
        "image": "https://www.gotokyo.org/es/destinations/southern-tokyo/images/499_0354_2.jpg",
        "name": "Tokyo",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Japon",
    },
    {
        "id": 3,
        "image": "https://a.travel-assets.com/findyours-php/viewfinder/images/res70/498000/498747-taipei.jpg",
        "name": "Taipéi",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 4,
        "image": "https://d500.epimg.net/cincodias/imagenes/2017/11/24/fortunas/1511544661_256825_1511544839_noticia_normal.jpg",
        "name": "Kuala Lumpur",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Malasia",
    },
    {
        "id": 5,
        "image": "https://www.larazon.es/resizer/OOuwHDQP_F2N6Gp-_EqU8ho1O88=/600x400/smart/filters:format(jpg)/cloudfront-eu-central-1.images.arcpublishing.com/larazon/PGDBVBN74RHHBF2GP6WWR6QIKY.jpg",
        "name": "Asjabad",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Turkmenistán",
    },
    {
        "id": 6,
        "image": "https://www.rusiaparadescubrir.com/userfiles/images/mongolia/big/mongol_ulaanbator_new.jpg",
        "name": "Ulán Bator",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Mongolia",
    },
    {
        "id": 7,
        "image": "https://cdn2.civitatis.com/uzbekistan/taskent/taskent.jpg",
        "name": "Taskent",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Uzbekistan",
    },
    {
        "id": 8,
        "image": "https://cdn2.civitatis.com/kirguistan/biskek/biskek.jpg",
        "name": "Biskek",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Kirguistán",
    },
    {
        "id": 9,
        "image": "https://funik.ru/wp-content/uploads/2021/01/30ed75f83b6a76603984.jpg",
        "name": "Almatý",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Kazajistán",
    },
    {
        "id": 10,
        "image": "https://cdn2.civitatis.com/tayikistan/dusambe/dusambe.jpg",
        "name": "Dusambé",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Tayikistán",
    },
    {
        "id": 11,
        "image": "https://mochilerosentailandia.com/wp-content/uploads/2016/07/hanoi-vista-panoramica.jpg",
        "name": "Hanói",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Vietnam",
    },
    {
        "id": 12,
        "image": "https://drscdn.500px.org/photo/99627869/m%3D900/v2?sig=8d10bc343d8ce30c86c2995d8bbcee661f1b667c6b3861b28be9f810d881dfd9",
        "name": "Manila",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Feria de Comida",
        "country": "Filipinas",
    },
    {
        "id": 13,
        "image": "https://cdn.getyourguide.com/img/location/5ad4fcac9cb97.jpeg/75.jpg",
        "name": "Bangkok",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Tailandia",
    },
    {
        "id": 14,
        "image": "https://media.driveboo.com/assets-image/768x420/8045b325-d1f8-4c31-b536-5c5e64c9ff02.jpg",
        "name": "Nom Pen",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Camboya",
    },
    {
        "id": 15,
        "image": "https://vamonos.asia/wp-content/uploads/2019/11/vientiane-to-hanoi.jpg",
        "name": "Vientián",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Laos",
    },
    {
        "id": 16,
        "image": "https://vamonos.asia/wp-content/uploads/2019/08/rangun-to-mandalay.jpg",
        "name": "Rangun",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Myanmar",
    },
    {
        "id": 17,
        "image": "https://viajamosjuntos.com.ar/wp-content/uploads/2020/12/portada-1.png",
        "name": "Bandar Seri Begawan",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Brunéi",
    },
    {
        "id": 18,
        "image": "https://content.r9cdn.net/rimg/dimg/d8/11/3f8093fd-city-304658-169b6573892.jpg?width=1200&height=630&crop=true",
        "name": "Timbu",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Bután",
    },
    {
        "id": 19,
        "image": "https://www.elagoradiario.com/wp-content/uploads/2020/11/shutterstock_1134436058-1024x576.jpg",
        "name": "Daca",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Bangladesh",
    },
    {
        "id": 20,
        "image": "https://www.liderempresarial.com/wp-content/uploads/2020/02/singapur12.jpg",
        "name": "Singapur",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Singapur",
    }
]

export default ciudades;