const ciudades = [
    {
        "id": 1,
        "image": "Feria de comidas7.jpg",
        "name": "Beijing",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 2,
        "image": "Feria de comidas7.jpg",
        "name": "Tokyo",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Feria de Comida",
        "country": "Salón A",
    },
    {
        "id": 3,
        "image": "Feria de comidas7.jpg",
        "name": "Taipéi",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 4,
        "image": "Feria de comidas7.jpg",
        "name": "Kuala Lumpur",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 5,
        "image": "Feria de comidas7.jpg",
        "name": "Asjabad",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 6,
        "image": "Feria de comidas7.jpg",
        "name": "Ulán Bator",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 7,
        "image": "Feria de comidas7.jpg",
        "name": "Taskent",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 8,
        "image": "Feria de comidas7.jpg",
        "name": "Biskek",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 9,
        "image": "Feria de comidas7.jpg",
        "name": "Almatý",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 10,
        "image": "Feria de comidas7.jpg",
        "name": "Dusambé",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 11,
        "image": "Feria de comidas7.jpg",
        "name": "Hanói",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 12,
        "image": "Feria de comidas7.jpg",
        "name": "Manila",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Feria de Comida",
        "country": "Salón A",
    },
    {
        "id": 13,
        "image": "Feria de comidas7.jpg",
        "name": "Bangkok",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 14,
        "image": "Feria de comidas7.jpg",
        "name": "Nom Pen",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 15,
        "image": "Feria de comidas7.jpg",
        "name": "Vientián",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 16,
        "image": "Feria de comidas7.jpg",
        "name": "Naipyidó",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 17,
        "image": "Feria de comidas7.jpg",
        "name": "Bandar Seri Begawan",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 18,
        "image": "Feria de comidas7.jpg",
        "name": "Timbu",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 19,
        "image": "Feria de comidas7.jpg",
        "name": "Daca",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    },
    {
        "id": 20,
        "image": "Feria de comidas7.jpg",
        "name": "Singapur",
        "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
        "continent": "Asia",
        "country": "Salón A",
    }
]

export default ciudades;